substitutions:
  pcf_inputs:
    '01': [pcf_inputs_1to14, 0]
    '02': [pcf_inputs_1to14, 1]
    '03': [pcf_inputs_1to14, 2]
    '04': [pcf_inputs_1to14, 3]
    '05': [pcf_inputs_1to14, 4]
    '06': [pcf_inputs_1to14, 5]
    '07': [pcf_inputs_1to14, 6]
    '08': [pcf_inputs_1to14, 8]
    '09': [pcf_inputs_1to14, 9]
    '10': [pcf_inputs_1to14, 10]
    '11': [pcf_inputs_1to14, 11]
    '12': [pcf_inputs_1to14, 12]
    '13': [pcf_inputs_1to14, 13]
    '14': [pcf_inputs_1to14, 14]
    '15': [pcf_inputs_15to28, 6]
    '16': [pcf_inputs_15to28, 5]
    '17': [pcf_inputs_15to28, 4]
    '18': [pcf_inputs_15to28, 3]
    '19': [pcf_inputs_15to28, 2]
    '20': [pcf_inputs_15to28, 1]
    '21': [pcf_inputs_15to28, 0]
    '22': [pcf_inputs_15to28, 8]
    '23': [pcf_inputs_15to28, 9]
    '24': [pcf_inputs_15to28, 10]
    '25': [pcf_inputs_15to28, 11]
    '26': [pcf_inputs_15to28, 12]
    '27': [pcf_inputs_15to28, 13]
    '28': [pcf_inputs_15to28, 14]
    '29': [pcf_inputs_28to35_menu, 0]
    '30': [pcf_inputs_28to35_menu, 1]
    '31': [pcf_inputs_28to35_menu, 2]
    '32': [pcf_inputs_28to35_menu, 3]
    '33': [pcf_inputs_28to35_menu, 4]
    '34': [pcf_inputs_28to35_menu, 5]
    '35': [pcf_inputs_28to35_menu, 6]
  pcf_inputs_next:
    '01': [pcf_inputs_1to14, 1]
    '02': [pcf_inputs_1to14, 2]
    '03': [pcf_inputs_1to14, 3]
    '04': [pcf_inputs_1to14, 4]
    '05': [pcf_inputs_1to14, 5]
    '06': [pcf_inputs_1to14, 6]
    '07': [pcf_inputs_1to14, 8]
    '08': [pcf_inputs_1to14, 9]
    '09': [pcf_inputs_1to14, 10]
    '10': [pcf_inputs_1to14, 11]
    '11': [pcf_inputs_1to14, 12]
    '12': [pcf_inputs_1to14, 13]
    '13': [pcf_inputs_1to14, 14]
    '14': [pcf_inputs_15to28, 6]
    '15': [pcf_inputs_15to28, 5]
    '16': [pcf_inputs_15to28, 4]
    '17': [pcf_inputs_15to28, 3]
    '18': [pcf_inputs_15to28, 2]
    '19': [pcf_inputs_15to28, 1]
    '20': [pcf_inputs_15to28, 0]
    '21': [pcf_inputs_15to28, 8]
    '22': [pcf_inputs_15to28, 9]
    '23': [pcf_inputs_15to28, 10]
    '24': [pcf_inputs_15to28, 11]
    '25': [pcf_inputs_15to28, 12]
    '26': [pcf_inputs_15to28, 13]
    '27': [pcf_inputs_15to28, 14]
    '28': [pcf_inputs_28to35_menu, 0]
    '29': [pcf_inputs_28to35_menu, 1]
    '30': [pcf_inputs_28to35_menu, 2]
    '31': [pcf_inputs_28to35_menu, 3]
    '32': [pcf_inputs_28to35_menu, 4]
    '33': [pcf_inputs_28to35_menu, 5]
    '34': [pcf_inputs_28to35_menu, 6]
