packages:
  pcf_config: !include ../pcf_configuration.yaml

substitutions:
  cover_name: "Cover"
  cover_output_pin: "REQUIRED_OUTPUT_PIN"
  cover_open_switch: "REQUIRED_OPEN_SWITCH"
  cover_close_switch: "REQUIRED_CLOSE_SWITCH"
  cover_open_duration: "10s"
  cover_close_duration: "10s"

cover:
  - platform: time_based
    name: ${cover_name}
    id: cover_${cover_output_pin}
    open_action:
      - switch.turn_on: ${cover_open_switch}
    open_duration: ${cover_open_duration}
    close_action:
      - switch.turn_on: ${cover_close_switch}
    close_duration: ${cover_close_duration}
    stop_action:
      - switch.turn_off: ${cover_open_switch}
      - switch.turn_off: ${cover_close_switch}

binary_sensor:
  - platform: gpio
    name: ${cover_name} Open
    id: cover_${cover_output_pin}_open
    internal: true
    pin:
      pcf8574: ${pcf_inputs[cover_output_pin][0]}
      number: ${pcf_inputs[cover_output_pin][1]}
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.open: cover_${cover_output_pin}
    on_release:
      then:
        - cover.stop: cover_${cover_output_pin}

  - platform: gpio
    name: ${cover_name} Close
    id: cover_${cover_output_pin}_close
    internal: true
    pin:
      pcf8574: ${pcf_inputs_next[cover_output_pin][0]}
      number: ${pcf_inputs_next[cover_output_pin][1]}
      mode:
        input: true
      inverted: true
    on_press:
      then:
        - cover.close: cover_${cover_output_pin}
    on_release:
      then:
        - cover.stop: cover_${cover_output_pin}
